apiVersion: skaffold/v2beta12
kind: Config
metadata:
  name: ktor
build:
  artifacts:
    - image: ktor-keepcalm
      jib:
        type: gradle
      context: .
  tagPolicy:
    sha256: {}
deploy:
  kubectl:
    manifests:
    - k8s/deployment.yaml
    - k8s/service.yaml
